import { Currencies } from "./Currencies";
import { Idd } from "./Idd";
import { Translation } from "./Translation";
import { Demonyms } from "./Demonyms";
import { Maps } from "./Maps";
import { Gini } from "./Gini";
import { Car } from "./Car";
import { CoatOfArms } from "./CoatOfArms";
import { PostalCode } from "./PostalCode";
import { Languages } from "./Languages";
import { Name } from "./Name";
import { CapitalInfo } from "./CapitalInfo";

export interface Country {
  name: Name;
  tld: string[];
  cca2: string;
  ccn3: string;
  cca3: string;
  cioc: string;
  independent: boolean;
  status: string;
  unMember: boolean;
  currencies: Currencies;
  idd: Idd;
  capital: string[];
  altSpellings: string[];
  region: string;
  subregion: string;
  languages: Languages;
  translations: { [key: string]: Translation };
  latlng: number[];
  landlocked: boolean;
  borders: string[];
  area: number;
  demonyms: Demonyms;
  flag: string;
  maps: Maps;
  population: number;
  gini: Gini;
  fifa: string;
  car: Car;
  timezones: string[];
  continents: string[];
  flags: CoatOfArms;
  coatOfArms: CoatOfArms;
  startOfWeek: string;
  capitalInfo: CapitalInfo;
  postalCode: PostalCode;
}
